image: golang:1.21-alpine  

stages:
  - build
  - deploy  

cache:
  paths:
    - go/pkg/mod  

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
    - go mod download  
    - go build .  

deploy:  
  stage: deploy
  script:
    - go mod download  
    - go build .
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -o StrictHostKeyChecking=no -r myutilityx.com $USER@$IP_ADDRESS:/tmp/
    - ssh $USER@$IP_ADDRESS "bash /home/ubuntu/deployments/deploy.sh"


  artifacts:
    paths:
      - myutilityx.com  
  only:
    - master 