image: golang:1.21-alpine  

stages:
  - build
  - build-docker
  - deploy  

cache:
  paths:
    - go/pkg/mod  

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
    - go mod download  
    - go build .  

build image:
  stage: build-docker
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy:  
  stage: deploy
  script:
    - go mod download  
    - go build .
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -o StrictHostKeyChecking=no -r myutilityx.com $USER@$IP_ADDRESS:/tmp/
    - ssh $USER@$IP_ADDRESS "bash /home/ubuntu/deployments/deploy-backend.sh"


  artifacts:
    paths:
      - myutilityx.com  
  only:
    - master 