image: golang:1.21-alpine

stages:
  - build
  - build-docker
  - deploy

cache:
  paths:
    - go/pkg/mod

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
    - go mod download
    - go build .

build image:
  stage: build-docker
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker compose build
    - docker tag mux_backend $DOCKER_IMAGE_TAG
    - docker push
  # only:
  #   - master

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # - "which ssh-agent || ( apk update && apk add openssh-client )"
    # - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # - ssh $USER@$IP_ADDRESS "mkdir -p /"
    - ssh $USER@$IP_ADDRESS "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    # Pull the latest images as per docker-compose.yml
    - ssh $USER@$IP_ADDRESS "cd / && docker-compose pull"
    # Stop, remove, and redeploy containers as per docker-compose.yml
    - ssh $USER@$IP_ADDRESS "cd / && docker-compose down"
    - ssh $USER@$IP_ADDRESS "cd / && docker-compose up -d --build"
    # - scp ./docker-compose.yml $USER@$IP_ADDRESS:/
    # - scp ./Dockerfile $USER@$IP_ADDRESS:/
    # - ssh $USER@$IP_ADDRESS "cd / && docker-compose -p back-app pull"
    # - ssh $USER@$IP_ADDRESS "cd / && docker-compose -p back-app up -d --build"
  artifacts:
    paths:
      - myutilityx.com
  # only:
  #   - master
