image: docker

services:
  - docker: dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
   - echo run tests in this section

build:
  stage: build
  script:
    - go mod download
    - go build -o my-app .
   
stage-deploy-prod:
  stage: deploy
  only:
    - master
  script: 
    - docker-compose up -d
    