services:
  mongodb:
    container_name: database_container
    image: mongo:latest
    platform: linux/arm64
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - my-network
volumes:
  mongodb: {}
networks:
  my-network:
    driver: bridge
