version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URL: ${MONGO_URL}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
        API_URL: ${API_URL}
        UI_URL: ${UI_URL}
    ports:
      - 8080:8080
    depends_on:
      - mongodb
volumes:
  mongodb: {}