version: '3.8'
services:
  app:
    image: golang:1.22.0-bookworm
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run .
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo:7.0
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${INIT_DB}
volumes:
  mongodb_data: