version: "3.8"
services:
  mongodb:
    container_name: database_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
  mux_backend:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_DB_NAME: myutilityx
      API_URL: https://api.mux.com
      UI_URL: https://mux.com
    depends_on:
      - mongodb
    networks:
      - my-network
volumes:
  mongodb: {}
