package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"myutilityx.com/graph/model"
	"myutilityx.com/repository"
)

// CreateContact is the resolver for the createContact field.
func (r *mutationResolver) CreateContact(ctx context.Context, contactInput *model.ContactInput) (*model.Contact, error) {
	if contactRepository == nil {
		return nil, fmt.Errorf("contact repository is not initialized")
	}
	contact, err := contactRepository.CreateContact(contactInput)
	if err != nil {
		return nil, err
	}
	return contact, nil
}

// GetContact is the resolver for the getContact field.
func (r *queryResolver) GetContact(ctx context.Context, id string) (*model.Contact, error) {
	if contactRepository == nil {
		return nil, fmt.Errorf("contact repository is not initialized")
	}
	contact, err := contactRepository.GetContact(id)
	if err != nil {
		return nil, err
	}
	return contact, nil
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	userID := ctx.Value("userId")
	// if !exist {
	// 	return nil, errors.New("Opps")
	// }
	return linkRepository.FindAllByUserID(userID.(primitive.ObjectID))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var linkRepository repository.LinkRepository = repository.New()
var contactRepository repository.ContactRepository = repository.NewContactRepository()
