// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Contact struct {
	ID        string     `json:"id"`
	Name      *string    `json:"name,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Message   *string    `json:"message,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	From      *string    `json:"from,omitempty"`
}

type ContactInput struct {
	Name    *string `json:"name,omitempty"`
	Email   *string `json:"email,omitempty"`
	Message *string `json:"message,omitempty"`
	From    *string `json:"from,omitempty"`
}

type Link struct {
	ID        string     `json:"id"`
	Name      *string    `json:"name,omitempty"`
	ShortURL  *string    `json:"shortUrl,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Clicks    *int       `json:"clicks,omitempty"`
	UserID    string     `json:"userId"`
}

type Mutation struct {
}

type Query struct {
}
